### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by lostchao11** [Bombaba/BlenderPythonScripts#5]
![report error](https://user-images.githubusercontent.com/7042169/31590452-5d64cd10-b1c5-11e7-899f-acae8d0fab34.png)
 Can not check box not sure if its because i'm using 2.79

**Comment by lostchao11** [comment]
I solved this problem you mush change the Encoding to UTF-8

**Comment by Bombaba** [comment]
It is very weird...
I always use UTF-8 when coding.
