### ISSUE TITLE
Error when trying to enable in 2.79 (encoded in UTF-8)

### ISSUE THREAD

**Issue by 3DNut** [Bombaba/BlenderPythonScripts#6]
![2017-11-12_161049](https://user-images.githubusercontent.com/18043007/32704565-96bd9910-c7c4-11e7-82c8-32a00ce97102.png)

I am getting the following error when I try and enable the add-on in Blender 2.79

**Comment by Bombaba** [comment]
I couldn't reproduce this issue.
Could you tell me how you downloaded this addon?

**Comment by 3DNut** [comment]
I clicked on RAW and selected all the code, copied and pasted it into a text file. I changed the extension to .py and opened it in Notepad ++ and converted it to UTF-8 and saved it out. At least that is how I remember doing it. Can you just provide me with a link to a working .py file?

**Comment by Bombaba** [comment]
Here it is:
https://gist.githubusercontent.com/Bombaba/1d4a98786130697052c25163ecefb760/raw/d0073c04d780517dd03742a2155c9ce05f1590f5/mesh_offset_edges.py

**Comment by 3DNut** [comment]
Thanks. I feel kinda dumb but I never realized I could RMB click and save as on the raw and just get the *.py file....I always copied the script and pasted it into a text file and renamed it. I am glad that I learned something new.
